/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.project.api;

import multi.project.core.Utils;

public class App {
    public static void main(String[] args) {
        boolean isAllPositiveNumbers = Utils.isAllPositiveNumbers("12", "79");

        System.out.println(isAllPositiveNumbers);
    }
}
